services:
    dockfire:
        container_name: dockfire
        build:
          context: ./
          dockerfile: Dockerfile
        image: dockfire
        ports:
          - 5900:5900
        command: x11vnc -forever -create
        volumes:
          - /data/iso:/data
        restart: unless-stopped
